- name: install java
  apt: pkg=openjdk-7-jre-headless state=present

- name: add logstash repo key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: add logstash repo
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/1.4/debian stable main" state=present

- name: install logstash
  apt: pkg=logstash state=present

- name: install logstash-contrib
  apt: pkg=logstash-contrib state=present

- name: start logstash
  service: name=logstash state=started

- name: copy logstash config
  template: src=logstash.conf dest=/etc/logstash/conf.d/logstash.conf
  notify:
  - restart logstash
