- name: install java
  apt: pkg=openjdk-7-jre-headless state=present

- name: add logstash repo key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: add logstash repo
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/1.4/debian stable main" state=present

- name: install logstash
  apt: pkg=logstash state=present

- name: install logstash-contrib
  apt: pkg=logstash-contrib state=present

- name: stop logstash service
  service: name=logstash state=stopped enabled=no

- name: copy monit file
  copy: src=logstash.monit dest=/etc/monit/conf.d/logstash.monit
  notify:
  - reload monit

- name: start logstash
  monit: name=logstash state=started
  ignore_errors: yes # TODO figure out why it isn't starting on es server

- name: copy logstash config
  template: src=logstash.conf dest=/etc/logstash/conf.d/logstash.conf
  notify:
  - restart logstash
