- name: add nginx repo
  apt_repository: repo=ppa:nginx/stable state=present
  register: add_nginx_ppa

- name: update package cache
  apt: update_cache=yes
  when: add_nginx_ppa.changed

- name: install nginx
  apt: pkg=nginx state=latest

- name: Remove nginx default site
  action: file path=/etc/nginx/sites-enabled/default state=absent

- name: copy nginx varnish config
  template: src=varnish.nginx.conf dest=/etc/nginx/sites-enabled/varnish
  register: varnish_nginx_conf

- name: reload nginx
  service: name=nginx state=reloaded
  when: varnish_nginx_conf.changed
