- name: add varnish apt key
  apt_key: url=http://repo.varnish-cache.org/debian/GPG-key.txt state=present

- name: add varnish repository
  copy: src=varnish.list dest=/etc/apt/sources.list.d/varnish.list

- name: install varnish
  apt: pkg=varnish update_cache=yes

- name: copy varnish default file
  copy: src=default dest=/etc/default/varnish

- name: copy Varnish config
  template: dest=/etc/varnish/default.vcl src=default.vcl

- name: start varnish
  service: name=varnish state=started enabled=yes
  ignore_errors: yes
